// Core domain model for NutriPlan.

export type HealthCondition =
  | "hypertension"
  | "diabetes"
  | "high_cholesterol";

export type DietaryPreference =
  | "vegetarian"
  | "vegan"
  | "pescatarian"
  | "gluten_free"
  | "dairy_free"
  | "nut_free";

export type CalorieGoal = "cutting" | "maintenance" | "bulking";

export type MealType = "breakfast" | "lunch" | "dinner" | "snack";

export type GroceryCategory =
  | "produce"
  | "protein"
  | "dairy"
  | "grains"
  | "pantry"
  | "frozen"
  | "other";

/** A single person's settings that drive plan generation. */
export interface Profile {
  id: string;
  name: string;
  healthConditions: HealthCondition[];
  dietaryPreferences: DietaryPreference[];
  calorieGoal: CalorieGoal;
  /** Daily calorie target in kcal. */
  targetCalories: number;
}

/** A grocery ingredient with an amount, used in meals and the shopping list. */
export interface Ingredient {
  name: string;
  /** Numeric quantity in the given unit (e.g. 2 of "cup"). */
  quantity: number;
  unit: string;
  /** Aisle/category used to group the consolidated grocery list. */
  category: GroceryCategory;
}

/** A single meal generated by the model for one slot of a day. */
export interface GeneratedMeal {
  mealType: MealType;
  name: string;
  description: string;
  /** Estimated calories for this meal. */
  calories: number;
  /** Macros in grams. */
  protein: number;
  carbs: number;
  fat: number;
  prepMinutes: number;
  ingredients: Ingredient[];
}

/** One day of the plan. */
export interface DayPlan {
  /** Day index 0-6 (Mon-Sun). */
  day: number;
  meals: GeneratedMeal[];
  /** Sum of meal calories — computed server-side after generation. */
  totalCalories: number;
}

/** A full one-week plan for a single profile. */
export interface WeekPlan {
  profileId: string;
  profileName: string;
  calorieGoal: CalorieGoal;
  targetCalories: number;
  /** ISO timestamp of when the plan was generated. */
  generatedAt: string;
  /** True when produced by demo/preview mode rather than the live API. */
  sample?: boolean;
  days: DayPlan[];
}

/** One line in the consolidated grocery list. */
export interface GroceryItem {
  name: string;
  quantity: number;
  unit: string;
  category: GroceryCategory;
}
